// src/data/parkingData.ts

export interface ParkingSpot {
  id: string;
  name: string;
  address: string;
  city: string;
  district: string;
  images: string[];
  pricePerHour: number;
  description: string;
  amenities: string[];
  ratings: {
    facilities: number;
    cleanliness: number;
    valueForMoney: number;
    staff: number;
    safety: number;
  };
  nearby: string[];
}

export const parkingData: ParkingSpot[] = [
  {
    id: "park1",
    name: "Nguyen Van Troi Parking",
    address: "123 Nguyen Van Troi, Da Nang",
    city: "Đà Nẵng",
    district: "Ngũ Hành Sơn",
    images: ["/park1.jpg", "/park2.jpg"],
    pricePerHour: 20000,
    description:
      "Spacious, secure parking near city center. 24/7 service, CCTV, and easy access.",
    amenities: ["24/7 access", "Security camera", "Shaded area", "Motorbike & Car"],
    ratings: {
      facilities: 85,
      cleanliness: 90,
      valueForMoney: 80,
      staff: 88,
      safety: 92,
    },
    nearby: [
      "🍽️ Seafood restaurant (300m)",
      "🏖️ My Khe Beach (1.2km)",
      "🏨 Grand Hotel (500m)",
      "⛽ Gas Station (200m)",
      "✈️ Da Nang Airport (4km)",
    ],
  },
  {
    id: "park2",
    name: "Motorbike Lot - Center",
    address: "45 Tran Phu, Da Nang",
    city: "Đà Nẵng",
    district: "Hải Châu",
    images: ["/park2.jpg"],
    pricePerHour: 10000,
    description: "Dedicated parking for motorbikes, safe and convenient in central Da Nang.",
    amenities: ["Motorbike only", "Night guard", "Easy access"],
    ratings: {
      facilities: 78,
      cleanliness: 82,
      valueForMoney: 90,
      staff: 85,
      safety: 88,
    },
    nearby: ["🏪 24h Store", "🏫 University", "🏖️ Riverfront"],
  },
  {
    id: "park3",
    name: "Truck & Bus Depot",
    address: "Km10 Highway, Hoa Vang",
    city: "Đà Nẵng",
    district: "Hòa Vang",
    images: ["/park3.jpg"],
    pricePerHour: 30000,
    description: "Large outdoor lot for buses and trucks, 24/7 monitored with wide lanes.",
    amenities: ["Truck access", "CCTV", "Guarded", "Rest area"],
    ratings: {
      facilities: 80,
      cleanliness: 75,
      valueForMoney: 78,
      staff: 83,
      safety: 85,
    },
    nearby: ["⛽ Gas Station", "🍜 Roadside Restaurant", "🛠️ Vehicle Repair"],
  },
  {
    id: "airport",
    name: "Da Nang Airport Parking",
    address: "Da Nang International Airport",
    city: "Đà Nẵng",
    district: "Hải Châu",
    images: ["/Airport.jpg"],
    pricePerHour: 25000,
    description: "Convenient parking for travelers, right next to the terminal.",
    amenities: ["Covered", "CCTV", "Close to terminal", "EV charging"],
    ratings: {
      facilities: 88,
      cleanliness: 90,
      valueForMoney: 85,
      staff: 89,
      safety: 91,
    },
    nearby: ["✈️ Terminal", "☕ Coffee Shop", "🚖 Taxi Stand"],
  },
  {
    id: "overnight",
    name: "Overnight Parking",
    address: "78 Le Duan, Da Nang",
    city: "Đà Nẵng",
    district: "Thanh Khê",
    images: ["/overnight.jpg"],
    pricePerHour: 15000,
    description: "Safe overnight parking with security and covered zones.",
    amenities: ["Night security", "Covered", "Access card"],
    ratings: {
      facilities: 80,
      cleanliness: 85,
      valueForMoney: 88,
      staff: 82,
      safety: 90,
    },
    nearby: ["🏨 Hotel", "🍻 Bar", "🏺 Mall"],
  },
  {
    id: "mall",
    name: "Mall Parking",
    address: "Vincom Plaza, Da Nang",
    city: "Đà Nẵng",
    district: "Sơn Trà",
    images: ["/mall.jpg"],
    pricePerHour: 18000,
    description: "Indoor parking under shopping center, spacious and convenient.",
    amenities: ["Indoor", "Direct mall access", "Elevator"],
    ratings: {
      facilities: 87,
      cleanliness: 89,
      valueForMoney: 84,
      staff: 86,
      safety: 89,
    },
    nearby: ["🏺 Mall", "🍽️ Food Court", "🎦 Cinema"],
  },
  {
    id: "event",
    name: "Event Parking",
    address: "Stadium Zone, Da Nang",
    city: "Đà Nẵng",
    district: "Liên Chiểu",
    images: ["/event.jpg"],
    pricePerHour: 22000,
    description: "Temporary parking for events and large gatherings.",
    amenities: ["Wide lanes", "Volunteer staff", "Portable lights"],
    ratings: {
      facilities: 75,
      cleanliness: 70,
      valueForMoney: 83,
      staff: 80,
      safety: 78,
    },
    nearby: ["🏀 Stadium", "🎶 Concert Venue", "🌟 Fairground"],
  },
  {
    id: "basement",
    name: "Basement Parking",
    address: "Sunshine Tower, Da Nang",
    city: "Đà Nẵng",
    district: "Hải Châu",
    images: ["/Basement.jpg"],
    pricePerHour: 17000,
    description: "Secure basement parking in commercial building.",
    amenities: ["Underground", "Security gate", "Lift access"],
    ratings: {
      facilities: 86,
      cleanliness: 88,
      valueForMoney: 81,
      staff: 84,
      safety: 87,
    },
    nearby: ["🏢 Office Block", "☕ Cafe", "🏪 Supermarket"],
  },
  {
    id: "outdoor",
    name: "Outdoor Parking",
    address: "Park View Area, Da Nang",
    city: "Đà Nẵng",
    district: "Cẩm Lệ",
    images: ["/Outdoor.jpg"],
    pricePerHour: 12000,
    description: "Open-air parking near park and jogging area.",
    amenities: ["Spacious", "Trees for shade", "Easy entry/exit"],
    ratings: {
      facilities: 79,
      cleanliness: 76,
      valueForMoney: 85,
      staff: 80,
      safety: 82,
    },
    nearby: ["🌿 Park", "🏃 Track", "🍼 Kiosk"],
  },
  {
    id: "reserved",
    name: "Reserved Spots",
    address: "Central Business District, Da Nang",
    city: "Đà Nẵng",
    district: "Hải Châu",
    images: ["/Reserved Spots.jpg"],
    pricePerHour: 30000,
    description: "Reserved spots for monthly users or premium accounts.",
    amenities: ["Monthly rental", "Private area", "License plate recognition"],
    ratings: {
      facilities: 90,
      cleanliness: 91,
      valueForMoney: 79,
      staff: 87,
      safety: 95,
    },
    nearby: ["💼 Office Tower", "🏢 Co-working", "🏠 Apartments"],
  },
  {
    id: "ev",
    name: "EV Charging Lot",
    address: "Green Plaza, Da Nang",
    city: "Đà Nẵng",
    district: "Sơn Trà",
    images: ["/EVCharging.jpg"],
    pricePerHour: 22000,
    description: "Dedicated EV parking with fast chargers.",
    amenities: ["EV fast chargers", "App control", "24/7 access"],
    ratings: {
      facilities: 92,
      cleanliness: 93,
      valueForMoney: 90,
      staff: 90,
      safety: 94,
    },
    nearby: ["⚡ Charging Hub", "🌿 Green Park", "☕ Coffee Lounge"],
  },
  {
    id: "car",
    name: "Car Parking",
    address: "Central District, Da Nang",
    city: "Đà Nẵng",
    district: "Hải Châu",
    images: ["/park6.jpg"],
    pricePerHour: 15000,
    description: "Quick and safe parking option for your car right in the heart of the city.",
    amenities: ["Covered", "Security camera", "Easy access", "EV charging"],
    ratings: {
      facilities: 86,
      cleanliness: 88,
      valueForMoney: 84,
      staff: 87,
      safety: 90,
    },
    nearby: ["🍜 Noodle Shop", "🛒 Supermarket", "🏥 Clinic"],
  },
  {
    id: "motorbike",
    name: "Motorbike Parking",
    address: "Le Loi Street, Da Nang",
    city: "Đà Nẵng",
    district: "Hải Châu",
    images: ["/park5.jpg"],
    pricePerHour: 8000,
    description: "Fast entry motorbike parking close to office and commercial area.",
    amenities: ["Shaded", "Security camera", "Quick entry"],
    ratings: {
      facilities: 80,
      cleanliness: 85,
      valueForMoney: 89,
      staff: 82,
      safety: 87,
    },
    nearby: ["🏢 Office Building", "☕ Cafe", "🏬 Shopping Mall"],
  },
  {
    id: "large-vehicles",
    name: "Truck & Bus Parking",
    address: "Ring Road, Da Nang",
    city: "Đà Nẵng",
    district: "Liên Chiểu",
    images: ["/park4.jpg"],
    pricePerHour: 35000,
    description: "Spacious parking for large vehicles with dedicated entry lanes.",
    amenities: ["Wide lanes", "Truck wash", "Lighting", "CCTV"],
    ratings: {
      facilities: 83,
      cleanliness: 78,
      valueForMoney: 81,
      staff: 84,
      safety: 86,
    },
    nearby: ["🔧 Mechanic Shop", "🛏 Motel", "🍲 Eatery"]
  }
];
